---

- hosts: all
  become: true
  tasks:

  - name: Upgrade Ubuntu systems 
    apt:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == ["Debian", "ubuntu"]

  - name: Upgrade AlmaLinux systems
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "AlmaLinux"

